@userId=5c6dca8657d080095f82e66f
@apihost=http://localhost:3000

### Get user by id
GET {{apihost}}/users/{{userId}}

### Get all users
GET {{apihost}}/users?sort=location&lat=0&lng=0&offset=0&limit=5
// Queries:
// sort=location lat=0 lng=0

### Create user
POST {{apihost}}/users
Content-Type: application/json

{
  "firstName": "firstName",
  "lastName": "lastName",
  "location": {
    "coordinates": [4, 4],
    "name": "testName"
  }
}

### Update user by id
PUT  {{apihost}}/users/{{userId}}
Content-Type: application/json

{
  "location": {
    "coordinates": [22, 33],
    "name": "testName"
  }
}

### Delete user by id
DELETE  {{apihost}}/users/{{userId}}
